FROM python:3.8.3-slim-buster

ENV PYTHONDONTWRITEDYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code

RUN pip install --upgrade pip
COPY requirements.txt /code/
RUN pip install -r requirements.txt

#
#RUN apk update \
#    && apk add postgresql-dev gcc python3-dev musl-dev
#RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev

#RUN apt-get install python3-psycopg2

COPY wait.sh /code/
#RUN sed -i 's/\r$//g' /code/wait.sh
RUN chmod +x /code/wait.sh

#COPY wait.sh /code/
# Copy the Django project
COPY . /code/
RUN pip install psycopg2

