FROM python:3.10.6

ENV PYTHONDONTWRITEDYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code

RUN pip install --upgrade pip
COPY requirements.txt /code/
RUN pip install -r requirements.txt
#COPY uwsgi.sock /code/
#RUN chown 999:999 /code/uwsgi.sock

#COPY wait.sh /code/
#RUN sed -i 's/\r$//g' /code/wait.sh
#RUN chmod +x /code/wait.sh

#COPY wait.sh /code/
# Copy the Django project
COPY . /code/
#RUN pip install psycopg2==2.9.3
#RUN apt-get install build-essential python
#RUN apt-get install -y gss-ntlmssp
#RUN pip install uwsgi
#RUN apt-get install uwsgi-plugin-python3
#RUN pip install https://projects.unbit.it/downloads/uwsgi-lts.tar.gz
#RUN chmod +x /code/config/uwsgi_app.sock


