# Generated by Django 4.1 on 2023-05-15 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 14, 58, 10, 996470, tzinfo=datetime.timezone.utc)),
        ),
    ]
